/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as EnderecosRouteImport } from './routes/enderecos'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as PagamentoIdRouteImport } from './routes/pagamento.$id'
import { Route as EnderecosNovoRouteImport } from './routes/enderecos.novo'
import { Route as AdminRedefinirSenhaRouteImport } from './routes/admin.redefinir-senha'
import { Route as AdminRecuperarSenhaRouteImport } from './routes/admin.recuperar-senha'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPdvRouteImport } from './routes/admin.pdv'
import { Route as AdminMesasRouteImport } from './routes/admin.mesas'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImpressaoRouteImport } from './routes/admin.impressao'
import { Route as AdminGarconsRouteImport } from './routes/admin.garcons'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminEstoqueRouteImport } from './routes/admin.estoque'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminEntregasRouteImport } from './routes/admin.entregas'
import { Route as AdminCuponsRouteImport } from './routes/admin.cupons'
import { Route as AdminCozinhaRouteImport } from './routes/admin.cozinha'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCardapioRouteImport } from './routes/admin.cardapio'
import { Route as AdminCadastroRouteImport } from './routes/admin.cadastro'
import { Route as AdminAvaliacoesRouteImport } from './routes/admin.avaliacoes'
import { Route as PedidoIdAvaliarRouteImport } from './routes/pedido.$id.avaliar'
import { Route as AdminPedidosNovoRouteImport } from './routes/admin.pedidos.novo'
import { Route as ApiPublicCronExpirePixRouteImport } from './routes/api/public/cron/expire-pix'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecosRoute = EnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoIdRoute = PagamentoIdRouteImport.update({
  id: '/pagamento/$id',
  path: '/pagamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnderecosNovoRoute = EnderecosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => EnderecosRoute,
} as any)
const AdminRedefinirSenhaRoute = AdminRedefinirSenhaRouteImport.update({
  id: '/admin/redefinir-senha',
  path: '/admin/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecuperarSenhaRoute = AdminRecuperarSenhaRouteImport.update({
  id: '/admin/recuperar-senha',
  path: '/admin/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPdvRoute = AdminPdvRouteImport.update({
  id: '/admin/pdv',
  path: '/admin/pdv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMesasRoute = AdminMesasRouteImport.update({
  id: '/admin/mesas',
  path: '/admin/mesas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImpressaoRoute = AdminImpressaoRouteImport.update({
  id: '/admin/impressao',
  path: '/admin/impressao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGarconsRoute = AdminGarconsRouteImport.update({
  id: '/admin/garcons',
  path: '/admin/garcons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEstoqueRoute = AdminEstoqueRouteImport.update({
  id: '/admin/estoque',
  path: '/admin/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/admin/equipe',
  path: '/admin/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntregasRoute = AdminEntregasRouteImport.update({
  id: '/admin/entregas',
  path: '/admin/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCuponsRoute = AdminCuponsRouteImport.update({
  id: '/admin/cupons',
  path: '/admin/cupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCozinhaRoute = AdminCozinhaRouteImport.update({
  id: '/admin/cozinha',
  path: '/admin/cozinha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/admin/clientes',
  path: '/admin/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/admin/cardapio',
  path: '/admin/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCadastroRoute = AdminCadastroRouteImport.update({
  id: '/admin/cadastro',
  path: '/admin/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvaliacoesRoute = AdminAvaliacoesRouteImport.update({
  id: '/admin/avaliacoes',
  path: '/admin/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdAvaliarRoute = PedidoIdAvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => PedidoIdRoute,
} as any)
const AdminPedidosNovoRoute = AdminPedidosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const ApiPublicCronExpirePixRoute = ApiPublicCronExpirePixRouteImport.update({
  id: '/api/public/cron/expire-pix',
  path: '/api/public/cron/expire-pix',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/demo': typeof DemoRoute
  '/enderecos': typeof EnderecosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cozinha': typeof AdminCozinhaRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/garcons': typeof AdminGarconsRoute
  '/admin/impressao': typeof AdminImpressaoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/admin/redefinir-senha': typeof AdminRedefinirSenhaRoute
  '/enderecos/novo': typeof EnderecosNovoRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/pedido/$id': typeof PedidoIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
  '/pedido/$id/avaliar': typeof PedidoIdAvaliarRoute
  '/api/public/cron/expire-pix': typeof ApiPublicCronExpirePixRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/demo': typeof DemoRoute
  '/enderecos': typeof EnderecosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cozinha': typeof AdminCozinhaRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/garcons': typeof AdminGarconsRoute
  '/admin/impressao': typeof AdminImpressaoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/admin/redefinir-senha': typeof AdminRedefinirSenhaRoute
  '/enderecos/novo': typeof EnderecosNovoRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/pedido/$id': typeof PedidoIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
  '/pedido/$id/avaliar': typeof PedidoIdAvaliarRoute
  '/api/public/cron/expire-pix': typeof ApiPublicCronExpirePixRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/demo': typeof DemoRoute
  '/enderecos': typeof EnderecosRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/admin/avaliacoes': typeof AdminAvaliacoesRoute
  '/admin/cadastro': typeof AdminCadastroRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/cozinha': typeof AdminCozinhaRoute
  '/admin/cupons': typeof AdminCuponsRoute
  '/admin/entregas': typeof AdminEntregasRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/estoque': typeof AdminEstoqueRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/garcons': typeof AdminGarconsRoute
  '/admin/impressao': typeof AdminImpressaoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mesas': typeof AdminMesasRoute
  '/admin/pdv': typeof AdminPdvRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/recuperar-senha': typeof AdminRecuperarSenhaRoute
  '/admin/redefinir-senha': typeof AdminRedefinirSenhaRoute
  '/enderecos/novo': typeof EnderecosNovoRoute
  '/pagamento/$id': typeof PagamentoIdRoute
  '/pedido/$id': typeof PedidoIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/pedidos/novo': typeof AdminPedidosNovoRoute
  '/pedido/$id/avaliar': typeof PedidoIdAvaliarRoute
  '/api/public/cron/expire-pix': typeof ApiPublicCronExpirePixRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/buscar'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/demo'
    | '/enderecos'
    | '/pedidos'
    | '/privacidade'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/cadastro'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cozinha'
    | '/admin/cupons'
    | '/admin/entregas'
    | '/admin/equipe'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/garcons'
    | '/admin/impressao'
    | '/admin/login'
    | '/admin/mesas'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/recuperar-senha'
    | '/admin/redefinir-senha'
    | '/enderecos/novo'
    | '/pagamento/$id'
    | '/pedido/$id'
    | '/admin/'
    | '/admin/pedidos/novo'
    | '/pedido/$id/avaliar'
    | '/api/public/cron/expire-pix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/buscar'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/demo'
    | '/enderecos'
    | '/pedidos'
    | '/privacidade'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/cadastro'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cozinha'
    | '/admin/cupons'
    | '/admin/entregas'
    | '/admin/equipe'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/garcons'
    | '/admin/impressao'
    | '/admin/login'
    | '/admin/mesas'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/recuperar-senha'
    | '/admin/redefinir-senha'
    | '/enderecos/novo'
    | '/pagamento/$id'
    | '/pedido/$id'
    | '/admin'
    | '/admin/pedidos/novo'
    | '/pedido/$id/avaliar'
    | '/api/public/cron/expire-pix'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/auth'
    | '/buscar'
    | '/carrinho'
    | '/checkout'
    | '/conta'
    | '/demo'
    | '/enderecos'
    | '/pedidos'
    | '/privacidade'
    | '/termos'
    | '/admin/avaliacoes'
    | '/admin/cadastro'
    | '/admin/cardapio'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/cozinha'
    | '/admin/cupons'
    | '/admin/entregas'
    | '/admin/equipe'
    | '/admin/estoque'
    | '/admin/financeiro'
    | '/admin/garcons'
    | '/admin/impressao'
    | '/admin/login'
    | '/admin/mesas'
    | '/admin/pdv'
    | '/admin/pedidos'
    | '/admin/recuperar-senha'
    | '/admin/redefinir-senha'
    | '/enderecos/novo'
    | '/pagamento/$id'
    | '/pedido/$id'
    | '/admin/'
    | '/admin/pedidos/novo'
    | '/pedido/$id/avaliar'
    | '/api/public/cron/expire-pix'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  DemoRoute: typeof DemoRoute
  EnderecosRoute: typeof EnderecosRouteWithChildren
  PedidosRoute: typeof PedidosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AdminAvaliacoesRoute: typeof AdminAvaliacoesRoute
  AdminCadastroRoute: typeof AdminCadastroRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminCozinhaRoute: typeof AdminCozinhaRoute
  AdminCuponsRoute: typeof AdminCuponsRoute
  AdminEntregasRoute: typeof AdminEntregasRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminEstoqueRoute: typeof AdminEstoqueRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminGarconsRoute: typeof AdminGarconsRoute
  AdminImpressaoRoute: typeof AdminImpressaoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMesasRoute: typeof AdminMesasRoute
  AdminPdvRoute: typeof AdminPdvRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminRecuperarSenhaRoute: typeof AdminRecuperarSenhaRoute
  AdminRedefinirSenhaRoute: typeof AdminRedefinirSenhaRoute
  PagamentoIdRoute: typeof PagamentoIdRoute
  PedidoIdRoute: typeof PedidoIdRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  ApiPublicCronExpirePixRoute: typeof ApiPublicCronExpirePixRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecos': {
      id: '/enderecos'
      path: '/enderecos'
      fullPath: '/enderecos'
      preLoaderRoute: typeof EnderecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento/$id': {
      id: '/pagamento/$id'
      path: '/pagamento/$id'
      fullPath: '/pagamento/$id'
      preLoaderRoute: typeof PagamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enderecos/novo': {
      id: '/enderecos/novo'
      path: '/novo'
      fullPath: '/enderecos/novo'
      preLoaderRoute: typeof EnderecosNovoRouteImport
      parentRoute: typeof EnderecosRoute
    }
    '/admin/redefinir-senha': {
      id: '/admin/redefinir-senha'
      path: '/admin/redefinir-senha'
      fullPath: '/admin/redefinir-senha'
      preLoaderRoute: typeof AdminRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recuperar-senha': {
      id: '/admin/recuperar-senha'
      path: '/admin/recuperar-senha'
      fullPath: '/admin/recuperar-senha'
      preLoaderRoute: typeof AdminRecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pdv': {
      id: '/admin/pdv'
      path: '/admin/pdv'
      fullPath: '/admin/pdv'
      preLoaderRoute: typeof AdminPdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mesas': {
      id: '/admin/mesas'
      path: '/admin/mesas'
      fullPath: '/admin/mesas'
      preLoaderRoute: typeof AdminMesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/impressao': {
      id: '/admin/impressao'
      path: '/admin/impressao'
      fullPath: '/admin/impressao'
      preLoaderRoute: typeof AdminImpressaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/garcons': {
      id: '/admin/garcons'
      path: '/admin/garcons'
      fullPath: '/admin/garcons'
      preLoaderRoute: typeof AdminGarconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/estoque': {
      id: '/admin/estoque'
      path: '/admin/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AdminEstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/admin/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entregas': {
      id: '/admin/entregas'
      path: '/admin/entregas'
      fullPath: '/admin/entregas'
      preLoaderRoute: typeof AdminEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cupons': {
      id: '/admin/cupons'
      path: '/admin/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AdminCuponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cozinha': {
      id: '/admin/cozinha'
      path: '/admin/cozinha'
      fullPath: '/admin/cozinha'
      preLoaderRoute: typeof AdminCozinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/admin/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/admin/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cadastro': {
      id: '/admin/cadastro'
      path: '/admin/cadastro'
      fullPath: '/admin/cadastro'
      preLoaderRoute: typeof AdminCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avaliacoes': {
      id: '/admin/avaliacoes'
      path: '/admin/avaliacoes'
      fullPath: '/admin/avaliacoes'
      preLoaderRoute: typeof AdminAvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id/avaliar': {
      id: '/pedido/$id/avaliar'
      path: '/avaliar'
      fullPath: '/pedido/$id/avaliar'
      preLoaderRoute: typeof PedidoIdAvaliarRouteImport
      parentRoute: typeof PedidoIdRoute
    }
    '/admin/pedidos/novo': {
      id: '/admin/pedidos/novo'
      path: '/novo'
      fullPath: '/admin/pedidos/novo'
      preLoaderRoute: typeof AdminPedidosNovoRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/api/public/cron/expire-pix': {
      id: '/api/public/cron/expire-pix'
      path: '/api/public/cron/expire-pix'
      fullPath: '/api/public/cron/expire-pix'
      preLoaderRoute: typeof ApiPublicCronExpirePixRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnderecosRouteChildren {
  EnderecosNovoRoute: typeof EnderecosNovoRoute
}

const EnderecosRouteChildren: EnderecosRouteChildren = {
  EnderecosNovoRoute: EnderecosNovoRoute,
}

const EnderecosRouteWithChildren = EnderecosRoute._addFileChildren(
  EnderecosRouteChildren,
)

interface AdminPedidosRouteChildren {
  AdminPedidosNovoRoute: typeof AdminPedidosNovoRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosNovoRoute: AdminPedidosNovoRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface PedidoIdRouteChildren {
  PedidoIdAvaliarRoute: typeof PedidoIdAvaliarRoute
}

const PedidoIdRouteChildren: PedidoIdRouteChildren = {
  PedidoIdAvaliarRoute: PedidoIdAvaliarRoute,
}

const PedidoIdRouteWithChildren = PedidoIdRoute._addFileChildren(
  PedidoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  DemoRoute: DemoRoute,
  EnderecosRoute: EnderecosRouteWithChildren,
  PedidosRoute: PedidosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AdminAvaliacoesRoute: AdminAvaliacoesRoute,
  AdminCadastroRoute: AdminCadastroRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminCozinhaRoute: AdminCozinhaRoute,
  AdminCuponsRoute: AdminCuponsRoute,
  AdminEntregasRoute: AdminEntregasRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminEstoqueRoute: AdminEstoqueRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminGarconsRoute: AdminGarconsRoute,
  AdminImpressaoRoute: AdminImpressaoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMesasRoute: AdminMesasRoute,
  AdminPdvRoute: AdminPdvRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminRecuperarSenhaRoute: AdminRecuperarSenhaRoute,
  AdminRedefinirSenhaRoute: AdminRedefinirSenhaRoute,
  PagamentoIdRoute: PagamentoIdRoute,
  PedidoIdRoute: PedidoIdRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  ApiPublicCronExpirePixRoute: ApiPublicCronExpirePixRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
